version: 2.1
executorType: machine
jobs:
  build:
    working_directory: ~/inquiry-api-service-build
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers-legacy
    steps:
      - checkout:
          path: ~/inquiry-api-service-build
      - restore_cache:
          key: inquiry-api-service-build-cache-{{ checksum "pom.xml" }}
      - run:
          name: Run build
          command: |
            git clone $core_repo_url knowlg-core -b $core_release_tag
            cd ~/inquiry-api-service-build/knowlg-core && mvn clean install -DskipTests -Pknowlg-core
            cd ~/inquiry-api-service-build && mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: inquiry-api-service-build-cache-{{ checksum "pom.xml" }}

  unit-tests:
    working_directory: ~/inquiry-api-service-test
    docker:
      - image: circleci/openjdk:14-jdk-buster-node-browsers-legacy
      - image: circleci/redis:latest
    parallelism: 1
    steps:
      - checkout
          path: ~/inquiry-api-service-test
      - restore_cache:
          key: inquiry-api-service-test-cache-{{ checksum "pom.xml" }}
      - run:
          name: Setup environment and run tests
          command: |
          git clone $core_repo_url knowlg-core -b $core_release_tag
          cd ~/inquiry-api-service-test/knowlg-core && mvn clean install -DskipTests -Pknowlg-core
          cd ~/inquiry-api-service-test && bash vmsetup.sh
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex ".*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - save_cache:
          paths:
            - ~/.m2
          key: inquiry-api-service-test-cache-{{ checksum "pom.xml" }}
      - store_test_results:
          path: ~/test-results

workflows:
  version: 2.1
  build-then-test:
      jobs:
        - build
        - unit-tests:
            requires:
              - build
